### ISSUE TITLE
이미지 배포

### ISSUE THREAD

**Issue by flareseek** [likelion11-kangwon/OOTD_Backend#10]
## 필요한 기능
- 이미지 배포 기능 추가

## 해야 할 일 
- [x] 프론트에서 이미지 업로드시 이미지를 저장 후 url 생성
- [x] 해당 url을 db에 저장

## 추가 컨텍스트
- S3로 작업을 할지 다른 이미지 호스팅 서버를 사용할지 고민해봐야 할 것 같습니다.

**Comment by GamJaDo** [comment]
Complete
